### ISSUE TITLE
unknown shorthand flag: 'd' in -d

### ISSUE THREAD

**Issue by GrimPixel** [simjanos-dev/LinguaCafe#111]
```
Cloning into 'linguacafe'...
remote: Enumerating objects: 4024, done.
remote: Counting objects: 100% (793/793), done.
remote: Compressing objects: 100% (421/421), done.
remote: Total 4024 (delta 591), reused 495 (delta 372), pack-reused 3231
Receiving objects: 100% (4024/4024), 88.67 MiB | 23.64 MiB/s, done.
Resolving deltas: 100% (2736/2736), done.
unknown shorthand flag: 'd' in -d
See 'docker --help'.
```

**Comment by simjanos-dev** [comment]
What platform did you try to install it to, and what was the exact command that you ran? 

I think it may be a problem with your docker setup, `docker compose up -d` should work, it does have a -d flag. Found nothing related in google.

**Comment by GrimPixel** [comment]
`docker-compose` is a separate package on Arch Linux, which is the distribution mine is based upon. It says `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` after installing `docker-compose`.
It turns out I need to execute `systemctl start docker` and `systemctl enable docker`, then `sudo docker-compose up -d`.

**Comment by GrimPixel** [comment]
Would you like to add this description to README?

**Comment by simjanos-dev** [comment]
I don't think I should. I still do not understand why `docker compose up -d` didn't work. I did not know the difference before, but I googled it, and my understanding is that `docker-compose` was an older standalone version of docker-compose, and `docker compose` command is integrated now to docker itself. 

If your problem is related to a linux distribution, I don't want to add it to the readme. Docker is a requirement to install LinguaCafe, I think adding it to the readme should only be considered if the problem occurred after you had a working docker running. But I still do not understand what exactly caused the problem.

@sergiolaverde0 What do you think?

**Comment by sergiolaverde0** [comment]
Arch is one of the most minimal DIY (do-it-yourself) Linux distros out there so it expects users to grab side packages (like `docker-compose`) and enable services themselves instead doing so when installing the package like most distros out there. The majority of people out there that run Ubuntu/Debian won't ever have this problem.

I'm gonna be blunt and say that this is not **our** issue, Arch users should either take responsibility of maintaining their own system (this is nothing compared to some things that have happened in the past) or move a friendlier distro that takes care of these little details for them.

**Comment by GrimPixel** [comment]
I understand now. I shouldn't have asked it, shouldn't have cared about this program because I was incapable.

**Comment by simjanos-dev** [comment]
You should have asked, you did, and I did help you. I don't think we implied in any way that you are incapable, I definitely did not mean to do that. 

But I don't think we should add a guide for this problem to the readme file, it is a reasonable requirement for a dockerized software to have docker installed and running. 

You are a very capable person, otherwise you wouldn't have been able fix the problem that you had. You have found more information about it than I did.

**Comment by sergiolaverde0** [comment]
I'm sorry I reacted like that, I really shouldn't. Even if my decision of not considering this issue as a responsibility of our project was justified, they way I phrased it wasn't.

**Comment by GrimPixel** [comment]
Good. I accept it. This is over.
If there are any idea I found helpful, I'll still let you know.

**Comment by lef-est** [comment]
> But I don't think we should add a guide for this problem to the readme file, it is a reasonable requirement for a dockerized software to have docker installed and running.

For what it's worth I tried installing LinguaCafe on Synology and discovered Synology's docker package only comes with docker-compose (version 1.28.5) which gave me:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I am far less capable than the OP here, so I'm not sure which version should be used/specified if I do need to modify the .yml

**Comment by sergiolaverde0** [comment]
Hi, I was unaware of this issue since `docker-compose` (a separate command) has been deprecated for a while and we run `docker compose` (a docker plugin) instead, but my search suggests to add this line at the top of the file as a fix:
```
version: "3"
```
However, I'd rather you check if you can [install](https://docs.docker.com/compose/install/) the modern tooling or update your system to check if that installs it for you.

**Comment by lef-est** [comment]
> However, I'd rather you check if you can [install](https://docs.docker.com/compose/install/) the modern tooling or update your system to check if that installs it for you.

Thank you. Indeed I was missing a DSM system update that I was unaware of. This updates docker compose to v2.
