### ISSUE TITLE
Manual review not possible

### ISSUE THREAD

**Issue by TheNomad11** [simjanos-dev/LinguaCafe#133]
I noticed that I cannot review vocabulary as much as I would like to. It is the app that decides how often I am to review words.

I just clicked review, and there were only three words that I was able to review.  When I finished the review, and clicked again "Review", no review pages was displayed, but only the dashboard. This was not what I expected, but I suppose this is due to the spaced repitition system.  

I wish that we as admins and learners would have more control, and that we would be able to start manual reviews. What do you think?

**Comment by simjanos-dev** [comment]
> I wish that we as admins and learners would have more control, and that we would be able to start manual reviews. What do you think?

I completely agree, this is because I published LinguaCafe too early, and there are some important missing features. Also it is missing a user manual, and there are a lot of things that are not intuitive, and users do not understand because I haven't explained them anywhere. I will try to address these soon.

> this is due to the spaced repitition system.

Yes, that is correct. 

If you click on the three dots and select the Review option on a book or a chapter, you get a start review dialog where you have an option to review them in practice mode.

In practice mode:
- Your words' and phrases' review due date will not change.
- Your reviews do not count in daily review goals.
- You will also get cards which are due to a later date.

In short you can review every highlighted word and phrase without any levels, due dates or review goals changing.

![Screenshot_20240217_130634](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/07545a99-3c0e-430a-9318-50838612ceff)

This dialog option is currently missing when you click on the Review option from the sidebar menu. I will add this in the next update, and later I add more customizable review options. I will also display information instead of just redirecting users to the home page when there are no words left.

In the meantime, you can use this URL to review all your highlighted words and phrases in practice mode:
http://localhost:9191/review/true/-1/-1

Is this the exact feature you would like, or are there more options you would like to be added? 

Thank you for making the Issue, I completely forgot about this!

**Comment by simjanos-dev** [comment]
I'll leave this issue open until I add the missing dialog and the message instead of redirecting users. I'll open an other issue for more review options later on. If you have further ideas for it, please comment it here or open a new issue.

Thank you too for taking the time figuring out!
