### ISSUE TITLE
docker-compose needs to be installed

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#160]
On macOS, I had to install `docker-compose`, which I did using Homebrew:

```
brew install docker-compose
```

When starting up the Docker container, the command is:

```
chmod -R 777 ./ && docker-compose up -d
```

**Comment by simjanos-dev** [comment]
In the readme there is a requirement for docker desktop to be installed, and I think even the base docker package includes docker-compose. 

(I've decided on docker desktop instead of docker, because there is a significant amount of people who are not familiar with docker but want to use linguacafe, and I think they will have a better experience with docker desktop.)

Is docker-compose something that you needed to be install on top of existing docker installation?

**Comment by uzluisf** [comment]
>In the readme there is a requirement for docker desktop to be installed, and I think even the base docker package includes docker-compose.

Interesting! I installed both the CLI and the desktop version but I also had to install `docker-compose`. It could be I had to close the terminal session for the command to be available in the PATH variable.

>(I've decided on docker desktop instead of docker, because there is a significant amount of people who are not familiar with docker but want to use linguacafe, and I think they will have a better experience with docker desktop.)

Yes, I do agree with this decision. I think LinguaCafe is a nice piece of software and it should be as accessible as possible.

>Is docker-compose something that you needed to be install on top of existing docker installation?

Yes, but again I might have messed something up during the installation. I think the command must be updated in the README since it's written `docker compose` instead of `docker-compose`.

Feel free to close this issue :)!
