### ISSUE TITLE
The manual is unclear about how to save words as phrases

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#184]
From https://simjanos-dev.github.io/LinguaCafeHome:

>You can also select multiple words, and save them as a phrase.

I've tried saving words as phrases but I haven't been able to do so. For example, I've tried clicking on words while holding the SHIFT key (and other keys) to make them into a phrase but I cannot seem to get it working.

**Comment by simjanos-dev** [comment]
Thank you for the feedback!

You can do it just like you do it in any text on a pc. Hold the left mouse button on a word, and drag it onto the next one. Except you have to start the selection on a word, you cannot start it on an empty space.

Someone said it was very slow in Brave browser. 

I will update the manual and add more clear explanations.

**Comment by uzluisf** [comment]
>You can do it just like you do it in any text on a pc. Hold the left mouse button on a word, and drag it onto the next one. Except you have to start the selection on a word, you cannot start it on an empty space.

This is awesome, thanks a lot!

>Someone said it was very slow in Brave browser recently.

I had to compress it due to Github's file size limit, however it's not slow on my end. I'm using Brave as well.

https://github.com/simjanos-dev/LinguaCafe/assets/22332927/34b65d35-afda-4b9e-81ff-884ddbea8d44

Again thanks a lot! Feel free to close this issue :)

**Comment by simjanos-dev** [comment]
> I had to compress it due to Github's file size limit, however it's not slow on my end. I'm using Brave as well.

Maybe he increased the chapter length limit, and it got laggy. I'm planning on improving performance. It is atrociously slow on longer texts, which was not a problem when only I used it, but haven't got to fix it yet since I published it.

> Again thanks a lot! Feel free to close this issue :)

I'll do that, but also added it to #174, and will explain it in the manual in more detail. If you have any more suggestions for the manual, please feel free to comment them there. 


Also, sorry about the e-ink theme, I haven't updated it for a long time. I will add a theme customization feature, probably in the next few months. It will allow you to completely customize word highlighting and theme colors. 

I really love your flag emoticons, it's a great idea. :) Maybe I should add it as an optional feature when clicking on translations.

**Comment by uzluisf** [comment]
Got it! It would've been helpful if he had described his setup.

>Also, sorry about the e-ink theme, I haven't updated it for a long time. I will add a theme customization feature, probably in the next few months. It will allow you to completely customize word highlighting and theme colors.

I actually like the simplicity of the e-ink theme :)

>I really love your flag emoticons, it's a great idea. :) Maybe I should add it as an optional feature when clicking on translations.

Yeah it's mostly serves as a visual hint for myself haha
