### ISSUE TITLE
Proposal: Various UI changes

### ISSUE THREAD

**Issue by sergiolaverde0** [simjanos-dev/LinguaCafe#186]
I have noticed some very small UI details that I think should be discussed to see if they are worth changing or not, which I have compiled in this issue:

- When importing the dictionaries supplied as tsv file they get added to the admin panel *below* the various DeepL options, even if they are disabled and the tsv are enabled. Since the list is long enough that one needs to scroll down to see the bottom, users might get confused and think the dictionary import failed. The proposal is to have enabled dictionaries always be at the top of the list.
- When swapping to the API tab of the admin panel the first thing the user is greeted with is an error message related to DeepL which is a bit blunt. I suppose this is due to it having an example token by default on an attempt to show what their token should look like. The proposal to silence the error, either by having the default token not raise an error or by leaving the field empty.
- On the same tab, the save button is not visible without scrolling down and fields that get changed down signal you in any way your changes have not been saved leading to confusion when the user leaves the tab without saving their changes the first time. The proposal is to add a small message when a field gets changed to warn the user about their changed not being saved.
- When adding a new book the save button remains greyed out after typing a valid name making it look like there is something wrong with the typed name, and the user needs to click in other spots of the page for it to go back to its normal color. This is the only part of the software where this happens as far as I know. The proposal is to have it go back to the normal, not greyed out color once the typed name is considered valid.
- If I hit the button to add a custom cover to a new book and then hit cancel the default cover is no longer an option unless I cancel the process and create a new book again. The proposal is to have the menu go back as it was before trying to add a custom cover, with the default cover.
- Add various points of the process of creating a new book and adding chapters, the 'enter' button does not allow to move on with the process and the user is forced to click on a button instead. When creating a new book 'enter' cancels the process, and when importing a book from epub it does nothing instead of moving you forward to the next step of the process. The proposal is to have 'enter' be the equivalent to clicking on 'next', 'ok', or the equivalent for the menu the user is at, if the current menu has been properly filled out.

If it sounds like I'm nitpicking, is because I'm. Most are very minor and didn't notice them until I spent a good while on the menus doing the testing for other features. I have compiled some screenshots in [this link](https://imgur.com/a/N4rbV8X) for added clarity.

**Comment by simjanos-dev** [comment]
> When importing the dictionaries supplied as tsv file they get added to the admin panel below the various DeepL options, even if they are disabled and the tsv are enabled. Since the list is long enough that one needs to scroll down to see the bottom, users might get confused and think the dictionary import failed. The proposal is to have enabled dictionaries always be at the top of the list.

I want to add a more complex filter function, and pagination for it. I also noticed that there are too many dictionaries now. Same goes for the library page. I'll also allow users to add and delete DeepL dictionaries. I think after that I should remove the default DeepL dictionaries, and let users add them for the languages they want, because it is not that difficult to add one, but it is annoying to have dozens of them that most users don't need/want.

> When swapping to the API tab of the admin panel the first thing the user is greeted with is an error message related to DeepL which is a bit blunt. I suppose this is due to it having an example token by default on an attempt to show what their token should look like. The proposal to silence the error, either by having the default token not raise an error or by leaving the field empty.

Good idea! I'll remove the error message for the default value.

> When adding a new book the save button remains greyed out after typing a valid name making it look like there is something wrong with the typed name, and the user needs to click in other spots of the page for it to go back to its normal color. This is the only part of the software where this happens as far as I know. The proposal is to have it go back to the normal, not greyed out color once the typed name is considered valid.

Also noticed it, and agree, it is annoying. I'll fix it.

> If I hit the button to add a custom cover to a new book and then hit cancel the default cover is no longer an option unless I cancel the process and create a new book again. The proposal is to have the menu go back as it was before trying to add a custom cover, with the default cover.

Good idea, I'll implement it.

> Add various points of the process of creating a new book and adding chapters, the 'enter' button does not allow to move on with the process and the user is forced to click on a button instead. When creating a new book 'enter' cancels the process, and when importing a book from epub it does nothing instead of moving you forward to the next step of the process. The proposal is to have 'enter' be the equivalent to clicking on 'next', 'ok', or the equivalent for the menu the user is at, if the current menu has been properly filled out.

I'll fix these as well.

> If it sounds like I'm nitpicking, is because I'm.

I don't think these are nitpicking, I noticed some of them as well, and they really are annoying. Thank you for writing a detailed issue.

**Comment by simjanos-dev** [comment]
> When swapping to the API tab of the admin panel the first thing the user is greeted with is an error message related to DeepL which is a bit blunt. I suppose this is due to it having an example token by default on an attempt to show what their token should look like. The proposal to silence the error, either by having the default token not raise an error or by leaving the field empty.

Fixed.

> When adding a new book the save button remains greyed out after typing a valid name making it look like there is something wrong with the typed name, and the user needs to click in other spots of the page for it to go back to its normal color. This is the only part of the software where this happens as far as I know. The proposal is to have it go back to the normal, not greyed out color once the typed name is considered valid.

Fixed. Also removed the "empty book name" error message until the user types in something.

> This is the only part of the software where this happens as far as I know.

It also happens on the import website and youtube section. However, in these case the code cannot be changed to validate and execute on keypresses, because it would try to send requests too many times. I was aware of it, but left it this way temporarily because the button did not fit on mobile screens. I'll go back before the next update, and fix it. I'll probably place the button below the url input field on mobile.

> If I hit the button to add a custom cover to a new book and then hit cancel the default cover is no longer an option unless I cancel the process and create a new book again. The proposal is to have the menu go back as it was before trying to add a custom cover, with the default cover.

Fixed. Clicking on cancel while creating a book will fall back on default image. If the user is editing a book that already has an image uploaded, then it will revert to the already existing image on cancel.

> When importing the dictionaries supplied as tsv file they get added to the admin panel below the various DeepL options, even if they are disabled and the tsv are enabled. Since the list is long enough that one needs to scroll down to see the bottom, users might get confused and think the dictionary import failed. The proposal is to have enabled dictionaries always be at the top of the list.

I've opened #199. After this is implemented, I don't think it is a good idea to change display order to show that a new dictionary has been added. The user already gets a green notification that the import was successful. What do you think?

![dictionary_import](https://github.com/simjanos-dev/LinguaCafe/assets/90243029/50440f61-4a33-4d7a-9e2d-e8e4ad00784f)



- [ ] Add various points of the process of creating a new book and adding chapters, the 'enter' button does not allow to move on with the process and the user is forced to click on a button instead. When creating a new book 'enter' cancels the process, and when importing a book from epub it does nothing instead of moving you forward to the next step of the process. The proposal is to have 'enter' be the equivalent to clicking on 'next', 'ok', or the equivalent for the menu the user is at, if the current menu has been properly filled out.
- [ ] Website and youtube import section does not auto update/validate on keypress,  will need a button.

These 2 are still unfinished.

**Comment by sergiolaverde0** [comment]
> I don't think it is a good idea to change display order to show that a new dictionary has been added. The user already gets a green notification that the import was successful. What do you think?

After the filters get added it would be a good alternative, as it would allow to filter by "installed only" and "not installed only" so that clutter would be reduced and visibility would have improved, so I like this solution.

**Comment by simjanos-dev** [comment]
Fixed everything except the dictionary page, which I moved into it's own issue, because it is a bigger task. Thank you for the feedback, they are not nitpicky, please send more if you find more problems with the UI.

**Comment by simjanos-dev** [comment]
On the last page of the import process you could not press enter immediately, because the form was not in focus. Added focus to the chapter length limit input when the page appears, so it can be imported by pressing enter.
