### ISSUE TITLE
[Feature Request] Select multiple non-contiguous words

### ISSUE THREAD

**Issue by uzluisf** [simjanos-dev/LinguaCafe#193]
Currently a user can select contiguous words to create a phrase. As a user I'd like to select multiple words for which I don't want to make a phrase but instead assign the same level, for example. A use case for this is ignoring multiple words in a text by selecting them all up front and then simply clicking the X button to ignore them, instead of having to select each word individually and then ignoring it.

I think a keyboard shortcut such as pressing `SHIFT` and left-clicking each word to be selected might be a suitable implementation. This will also likely require a new view for the sidebar where the selected words are listed, along with the level setting. It might not make sense to do a vocabulary look-up for this functionality.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/22332927/e1fc301f-7a35-4eeb-9723-2dbb7e7c1626)

**Comment by simjanos-dev** [comment]
Currently, if you hover over a word, you can use hotkeys (I think it's `x` to ignore, you can check on the last toolbar button) to change a word's level. This would have the same result, with less button click/button presses. You must also not have a word selected, because in that case the selected word's level will change instead of the hovered word's.

Does this work for you as well, or would you still like this feature?

I've also just had an idea and created #194.

**Comment by uzluisf** [comment]
>If you hover over a word, you can use hotkeys (I think it's x to ignore, you can check on the last toolbar button) to change a word's level. This would have the same result, with less clicks/button presses.

This is awesome! Thanks!

>Does this work for you as well, or would you still like this feature?

Yes, this addresses this issue so I'll close it :) Thanks a lot!
