### ISSUE TITLE
Statistics bug? Editing a finished text re-adds all words to the reading stats

### ISSUE THREAD

**Issue by TheNomad11** [simjanos-dev/LinguaCafe#200]
I checked a text that I have already marked as finished and added a new word to my vocabularyl I then clicked on "finish reading", and - voila, instead of 260 words, 520 words were in my reading stats. I think this is not intended behavior? In my view, the stats shouldn't change?

**Comment by simjanos-dev** [comment]
If I understand it correctly, it is intended behaviour. If you read a text multiple times, it should be counted in the reading statistics multiple times. If you are reviewing words or phrases those count as read words as well in the statistics. If you turn on the example sentence setting on the review page, it will count those as read words instead of the word or phrase.

> Editing a finished text re-adds all words to the reading stats

In the github issue's content you wrote about marking it finished. If click on the three dots and you edit the content of a chapter, that should not change your statistics.

> I think this is not intended behavior?

I can calculate and add a "Unique texts read" statistics if that's something you would like to see.

**Comment by TheNomad11** [comment]
Ok. that makes sense, thanks for the explanation! No nee to add "Unique texts read" - this would make everything too complex.

**Comment by simjanos-dev** [comment]
> Ok. that makes sense, thanks for the explanation!

Sure. I really need to work on the user manual, lot of stuff missing. 

> No nee to add "Unique texts read" - this would make everything too complex.

If you change your mind feel free to leave a comment, it is really easy to add, chapters are already marked in the database if they were read one time at least.
