### ISSUE TITLE
Github development

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#9]
Hi!

Can someone please help me with some github basics?

I've created a dev branch, which I plan to use to for development, and I only push working versions for the main branch with a new version number each time. 

I've got this message on github:

> Your main branch isn't protected
> Protect this branch from force pushing or deletion, or require status checks before merging.

I clicked on it, and created the default ruleset that github offered me. 

Can someone explain it to me what it is, and what should I be looking out for? Is there anything else important I should set up in github?

**Comment by sergiolaverde0** [comment]
Creating a separate dev branch is good, but it should be accompanied by adding a `` CONTRIBUTING.md`` file that informs people to only send pull requests there.

It would also be a good idea to add a license to the project as a whole, even if there's one in the header of some of the files, to make sure there's no ambiguity about the licensing of any files.

I have noticed you have tests, and I think you can have GitHub run tests for you on certain conditions so you don't forget to run them manually.

In the future it would be nice to have the docker images be built and hosted by GitHub too and change ``docker-compose.yml`` to simply pull from it, so that people don't have to build them locally. This last thing, however, might need some changes in the ``Dockerfile``, I will give that bit a try first in my fork.

**Comment by simjanos-dev** [comment]
Thank you!

I do not have tests, they were just created by Laravel by default.

I will make the contributing and license files.

**Comment by ararslan** [comment]
> I've got this message on github:
>
> > Your main branch isn't protected
> > Protect this branch from force pushing or deletion, or require status checks before merging.
>
> I clicked on it, and created the default ruleset that github offered me.
>
> Can someone explain it to me what it is, and what should I be looking out for?

There is a section in the GitHub documentation about branch protection [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) but it's a bit dense. The default branch in a repository (here, and most commonly, `main`) is usually pretty important, so GitHub provides some mechanisms, called "branch protection rules," to help ensure that any changes made to the branch are intentional. By default, two rules are applied:
- The branch can't be deleted, neither via the GitHub UI nor `git push origin --delete`. You'd lose all of your work on that branch!
- [Force pushes](https://git-scm.com/docs/git-push#Documentation/git-push.txt---force), i.e. `git push origin main --force`, are disallowed. This ensures existing commits aren't lost, since force pushing overwrites the commit history.

The linked documentation page explains the other options in more detail. In my opinion, the default options are sufficient for most cases. For projects with tests that run on a continuous integration service (e.g. GitHub Actions), it can be helpful to require that pull request status checks pass before a pull request can be merged. And for repositories with multiple active maintainers, requiring pull request reviews can also be worthwhile.

> I've created a dev branch, which I plan to use to for development

In that case, I recommend protecting that branch as well.

Hope this helps. Cool project!

**Comment by simjanos-dev** [comment]
I didn't understand it at first and was worried about that someone else could cause harm, but it does make perfect sense now, thank you!
