### ISSUE TITLE
Versions can not be easily pinned or rolled back to

### ISSUE THREAD

**Issue by sergiolaverde0** [simjanos-dev/LinguaCafe#90]
Since images are build in reaction to commits to `main`, their relationship with releases is a informal one. I didn't consider this originally to be an issue, but I have noticed that images don't have a proper version tag, and once the a new one is built and tagged as `main`the others are [left untagged](https://github.com/simjanos-dev/LinguaCafe/pkgs/container/linguacafe-webserver/versions?filters%5Bversion_type%5D=untagged) and their only way to access them is via their checksums, such as:

```
image: ghcr.io/simjanos-dev/linguacafe-webserver@sha256:134dda999ec0b1150238191826c7e3d97c58c3ed485475228a47f54ff4790aec
```

The proposal is to tie down the build of new images to a new release directly on the GitHub action to ensure old versions keep their version tags. It will still be possible to default to running the latest image by defining:

```
image: ghcr.io/simjanos-dev/linguacafe-webserver:latest
```

Which is more or less the norm among services distributed via Docker.

Edit: See an [example at my fork](https://github.com/sergiolaverde0/LinguaCafe/pkgs/container/linguacafe-webserver) where I build some things to test before opening a PR. Just never run any of them in production, please.

**Comment by simjanos-dev** [comment]
Thank you, that would be great! But how does it work?

- Currently it starts building when it's merged into main, which is before creating a new version tag and release. 
- What happens if someone updates it while the image is being built? Currently it would just use the previous image. 
- Where does `${VERSION:-main}` come from? GitHub creates the version environment variable before starts building the image?

Now I usually merge it into main, wait for it to finish building the images, and then I create the github release.

Can we do it in a separate PR from mysql password? I think I will merge in one of them, wait for a few days at least, and then merge in the other, so it's not overwhelming if there is a problem to fix, if that's okay with you.

What will I have to do to make it work?

**Comment by sergiolaverde0** [comment]
- It would only start building when the release is made, so a new download would pick the old image for the half hour it takes for the ARM image to finish. People trying to update won't download a image they already have, docker is smarter than that.
- Currently images are built based on events on a branch so that's where `main` comes from. After the changes they will be built based on a release being made so they will pick that as their tag.
- I like the idea of having it separate from the environment update, since that one can be deployed early as a hotfix, but this one must wait until next release.
- From the code side three lines must be commented out and replaced with another three.

**Comment by sergiolaverde0** [comment]
Done in #124 and #125.
